sudo: required
services: 
  - docker
  
before_install:
  - docker build -t spratt88/docker-course -f Dockerfile.dev .

script:
  - docker run -e CI=true spratt88/docker-course npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: elasticbeanstalk-us-east-2-891377349069
  bucket_path: "frontend"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"